version: '3.8'

services:
  # YouTube API MCP Server with HTTP transport
  youtube-api-mcp-server:
    image: ghcr.io/jordanburke/youtube-api-mcp-server:latest
    container_name: youtube-api-mcp-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Required: Your YouTube Data API key
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      # Optional: Default language for transcripts (defaults to 'en')
      YOUTUBE_TRANSCRIPT_LANG: ${YOUTUBE_TRANSCRIPT_LANG:-en}
      # HTTP transport configuration (defaults set in Dockerfile)
      MCP_TRANSPORT: ${MCP_TRANSPORT:-http}
      MCP_HTTP_PORT: ${MCP_HTTP_PORT:-3000}
      MCP_HTTP_HOST: ${MCP_HTTP_HOST:-0.0.0.0}
      # Node environment
      NODE_ENV: production
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Example: Testing the MCP server with stdio
  # test-client:
  #   image: node:20-alpine
  #   stdin_open: true
  #   tty: true
  #   command: |
  #     sh -c 'echo "{\"jsonrpc\":\"2.0\",\"method\":\"initialize\",\"params\":{\"capabilities\":{}},\"id\":1}" | 
  #            docker exec -i youtube-api-mcp-server node dist/index.js'
  #   depends_on:
  #     - youtube-api-mcp-server