name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Check formatting
        run: pnpm format:check
      
      - name: Run ESLint
        run: pnpm lint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run TypeScript type checking
        run: pnpm typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20', '22']
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build project
        run: pnpm build
      
      - name: Verify build output
        run: |
          # Check that required files exist
          test -f dist/index.js
          test -f dist/cli.js
          test -f dist/index.d.ts
          test -f dist/cli.d.ts
          
          # Verify shebang in CLI
          head -n1 dist/cli.js | grep -q "^#!/usr/bin/env node"
          
          # Check syntax
          node -c dist/index.js
          node -c dist/cli.js
      
      - name: Test CLI help
        run: |
          # Should fail with missing API key message
          if node dist/cli.js 2>&1 | grep -q "YOUTUBE_API_KEY"; then
            echo "CLI correctly requires API key"
          else
            echo "CLI did not show expected API key error"
            exit 1
          fi

  test-publish:
    name: Test npm publish
    runs-on: ubuntu-latest
    needs: [lint, typecheck, build]
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build project
        run: pnpm build
      
      - name: Test npm pack
        run: |
          npm pack --dry-run
          npm pack
          tar -tf youtube-api-mcp-server-*.tgz | grep -E "(dist/cli.js|dist/index.js|package.json|README.md)"